name: islamic360
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg:
  provider:
  shared_preferences:
  flutter_staggered_animations: ^1.1.1
  flutter_qiblah:
  audioplayers: ^1.0.1
  scroll_to_index: ^3.0.1
  sizer: ^2.0.15
  device_preview: ^1.1.0
  flutter_snake_navigationbar: ^0.6.1
  dio: ^5.0.0
  hive: ^2.2.3
  flutter_launcher_icons:


  hijri_picker:
    git:
      url: https://github.com/SamadDev/kurdish_hirji_date.git
      ref: main

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/quran_icon.png"

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/1024/
    - assets/icons/
    - assets/jsons/
    # - assets/audio/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: nrt
      fonts:
        - asset: assets/fonts/NRT-Reg.ttf

    - family: rudaw
      fonts:
        - asset: assets/fonts/rudaw.ttf

    - family: noor
      fonts:
        - asset: assets/fonts/noorehidayat.ttf

    - family: quran
      fonts:
        - asset: assets/fonts/quran.ttf

    - family: hafs
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf

    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf

    - family: albayan
      fonts:
        - asset: assets/fonts/AlBayan.ttf

    - family: tehran
      fonts:
        - asset: assets/fonts/BTehran.ttf

    - family: amir
      fonts:
        - asset: assets/fonts/Amir.ttf

    - family: quran1
      fonts:
        - asset: assets/fonts/quran1.ttf
    - family: quran_otf
      fonts:
        - asset: assets/fonts/qurn_otf.otf
#    - family: quran_qrf
#      fonts:
#        - asset: assets/fonts/qruan_qrf.otf

  #Amir
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
